// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnZ0dRG92rCNAjo6Qzy9ksR-MIvb7At8g',
    appId: '1:176036392836:web:e6392269d84ee7df6977d1',
    messagingSenderId: '176036392836',
    projectId: 'chefoo-1',
    authDomain: 'chefoo-1.firebaseapp.com',
    storageBucket: 'chefoo-1.firebasestorage.app',
    measurementId: 'G-XMQBD0QT0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8KceUgDzBX5K-6KFAWoZ1KtBQWcIUWgU',
    appId: '1:176036392836:android:8f4f7e7d4a9968d46977d1',
    messagingSenderId: '176036392836',
    projectId: 'chefoo-1',
    storageBucket: 'chefoo-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARxe5X81PXNO2He26SccXRHue8Ih2UdQk',
    appId: '1:176036392836:ios:61567d03e26fc45b6977d1',
    messagingSenderId: '176036392836',
    projectId: 'chefoo-1',
    storageBucket: 'chefoo-1.firebasestorage.app',
    androidClientId: '176036392836-26vdj2i0fqf66icfasr48gopltbplafp.apps.googleusercontent.com',
    iosClientId: '176036392836-o4g1i4e39m2su4u3l4n1mvir5nnn0ak9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSkeleton',
  );
}
