// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnZ0dRG92rCNAjo6Qzy9ksR-MIvb7At8g',
    appId: '1:176036392836:web:e6392269d84ee7df6977d1',
    messagingSenderId: '176036392836',
    projectId: 'chefoo-1',
    authDomain: 'chefoo-1.firebaseapp.com',
    storageBucket: 'chefoo-1.firebasestorage.app',
    measurementId: 'G-XMQBD0QT0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLI5MshJGP2NdxmhnH3MFxupSNGQu37ds',
    appId: '1:246856005380:android:77d8771e9a2c34f89b4251',
    messagingSenderId: '246856005380',
    projectId: 'chefoo-462422',
    storageBucket: 'chefoo-462422.firebasestorage.app',
  );

}